"""Pure-Python telluric fitting experiments inspired by ESO Molecfit."""

from ._version import __version__
from .aer_data import (
    AER_CATALOG_VERSION,
    AERCatalogArtifact,
    AERDataError,
    AERLineArtifact,
    aer_catalog_status,
    default_aer_cache_dir,
    find_local_aer_catalog,
    install_aer_catalog,
    load_aer_line_window,
)
from .atmosphere import AtmosphereLayer, AtmosphereProfile
from .components import (
    AbsorptionComponent,
    CO2ContinuumAbsorption,
    H2OContinuumAbsorption,
    HitranLineAbsorption,
    N2CIAAbsorption,
    N2ContinuumAbsorption,
    N2RototranslationalContinuumAbsorption,
    O2CIAAbsorption,
    O2ContinuumAbsorption,
    PairCIAAbsorption,
    RayleighScatteringAbsorption,
    TabulatedContinuumAbsorption,
    combine_optical_depth_components,
    line_wing_effective_cutoff_cm,
)
from .continuum import (
    CIABlock,
    HitranCIATable,
    LBLRTMCO2Continuum,
    LBLRTMH2OContinuum,
    LBLRTMN2FundamentalContinuum,
    LBLRTMN2OvertoneContinuum,
    LBLRTMO2Continuum,
    MTCKDH2OContinuum,
    TabulatedContinuum,
    cubic_interpolate_regular,
    lblrtm_n2_rototranslational_coefficients,
    lblrtm_n2_rototranslational_optical_depth,
    lblrtm_rayleigh_optical_depth,
    radiation_term_cm,
    radiation_term_interval_cm,
)
from .diagnostics import correction_summary, residual_by_window
from .fit import (
    FitConfig,
    MultiTelluricFitResult,
    TelluricFitResult,
    fit_telluric_segments,
    fit_tellurics,
)
from .hitran import (
    LBLRTM_ISOTOPOLOGUE_MASSES_AMU,
    lblrtm_isotopologue_mass_amu,
    read_aer_line_file,
    read_hitran_par,
)
from .io import load_spectrum, save_spectrum
from .linelist import LineList
from .line_data import (
    HitranAcquisitionError,
    HitranLineArtifact,
    cache_hitran_par,
    default_hitran_cache_dir,
    fetch_hitran_lines,
)
from .model import (
    ModelConfig,
    PiecewiseConstantRebinPlan,
    SampleAverageRebinPlan,
    average_high_resolution_values,
    high_resolution_wavelength_grid,
    lsf_kernel_half_width_pixels,
    optical_depth_basis,
    prepare_piecewise_constant_rebin,
    prepare_sample_average_rebin,
    radiative_transfer_wavelength_grid,
    rebin_piecewise_constant_values,
    rebin_high_resolution_values,
    sample_high_resolution_values,
    transmission_from_high_resolution_basis,
    transmission_model,
)
from .partition import IsotopologueMetadata, PartitionTable
from .plotting import plot_fit
from .physics import (
    lblrtm_dynamic_line_cutoff_cm,
    lblrtm_dynamic_max_line_cutoff_cm,
    lblrtm_f4_coefficients,
    lblrtm_layer_wavenumber_spacing_cm,
    lblrtm_layer_wavenumber_spacings_cm,
    lblrtm_merge_layer_wavenumber_spacings_cm,
    lblrtm_panel_interpolate_r1_r2_r3,
    lblrtm_panel_voigt_profile_wavenumber,
    lblrtm_tabulated_voigt_profile_offset,
    lblrtm_temperature_scaling_lower_energy,
    lblrtm_voigt_hwhm,
    pressure_shift_wavenumber,
)
from .radiative_transfer import (
    PhysicalModelConfig,
    hitran_optical_depth_basis,
    physical_components_from_options,
    physical_optical_depth_basis,
    physical_transmission_model,
)
from .spectrum import Spectrum, air_to_vacuum_wavelength, correct_spectrum, vacuum_to_air_wavelength
from .systematics import (
    ModelSystematicsResult,
    MultiModelSystematicsResult,
    fit_telluric_segments_with_systematics,
    fit_tellurics_with_systematics,
)
from .validation import (
    ScienceReadinessReport,
    SpectrumComparison,
    TelluricCrossValidationResult,
    ValidationCheck,
    compare_spectra,
    cross_validate_telluric_segments,
)
from .workflow import correct_arrays, correct_file

__all__ = [
    "__version__",
    "AER_CATALOG_VERSION",
    "AERCatalogArtifact",
    "AERDataError",
    "AERLineArtifact",
    "aer_catalog_status",
    "default_aer_cache_dir",
    "find_local_aer_catalog",
    "install_aer_catalog",
    "load_aer_line_window",
    "AbsorptionComponent",
    "AtmosphereLayer",
    "AtmosphereProfile",
    "CIABlock",
    "CO2ContinuumAbsorption",
    "FitConfig",
    "H2OContinuumAbsorption",
    "HitranCIATable",
    "HitranLineAbsorption",
    "HitranAcquisitionError",
    "HitranLineArtifact",
    "IsotopologueMetadata",
    "LineList",
    "LBLRTM_ISOTOPOLOGUE_MASSES_AMU",
    "LBLRTMCO2Continuum",
    "LBLRTMH2OContinuum",
    "LBLRTMN2FundamentalContinuum",
    "LBLRTMN2OvertoneContinuum",
    "LBLRTMO2Continuum",
    "ModelConfig",
    "ModelSystematicsResult",
    "MultiModelSystematicsResult",
    "MTCKDH2OContinuum",
    "MultiTelluricFitResult",
    "N2CIAAbsorption",
    "N2ContinuumAbsorption",
    "N2RototranslationalContinuumAbsorption",
    "O2CIAAbsorption",
    "O2ContinuumAbsorption",
    "PairCIAAbsorption",
    "PhysicalModelConfig",
    "PartitionTable",
    "PiecewiseConstantRebinPlan",
    "SampleAverageRebinPlan",
    "RayleighScatteringAbsorption",
    "Spectrum",
    "SpectrumComparison",
    "TelluricCrossValidationResult",
    "ScienceReadinessReport",
    "TabulatedContinuum",
    "TabulatedContinuumAbsorption",
    "TelluricFitResult",
    "ValidationCheck",
    "air_to_vacuum_wavelength",
    "correct_spectrum",
    "correct_arrays",
    "correct_file",
    "cache_hitran_par",
    "combine_optical_depth_components",
    "compare_spectra",
    "cross_validate_telluric_segments",
    "correction_summary",
    "cubic_interpolate_regular",
    "fit_tellurics",
    "fit_tellurics_with_systematics",
    "fetch_hitran_lines",
    "fit_telluric_segments",
    "fit_telluric_segments_with_systematics",
    "high_resolution_wavelength_grid",
    "lsf_kernel_half_width_pixels",
    "hitran_optical_depth_basis",
    "lblrtm_dynamic_line_cutoff_cm",
    "lblrtm_dynamic_max_line_cutoff_cm",
    "lblrtm_f4_coefficients",
    "lblrtm_isotopologue_mass_amu",
    "lblrtm_layer_wavenumber_spacing_cm",
    "lblrtm_layer_wavenumber_spacings_cm",
    "lblrtm_merge_layer_wavenumber_spacings_cm",
    "lblrtm_n2_rototranslational_coefficients",
    "lblrtm_n2_rototranslational_optical_depth",
    "lblrtm_panel_interpolate_r1_r2_r3",
    "lblrtm_panel_voigt_profile_wavenumber",
    "lblrtm_rayleigh_optical_depth",
    "lblrtm_tabulated_voigt_profile_offset",
    "lblrtm_temperature_scaling_lower_energy",
    "lblrtm_voigt_hwhm",
    "line_wing_effective_cutoff_cm",
    "default_hitran_cache_dir",
    "load_spectrum",
    "optical_depth_basis",
    "physical_components_from_options",
    "physical_optical_depth_basis",
    "physical_transmission_model",
    "plot_fit",
    "pressure_shift_wavenumber",
    "prepare_piecewise_constant_rebin",
    "prepare_sample_average_rebin",
    "radiative_transfer_wavelength_grid",
    "radiation_term_cm",
    "radiation_term_interval_cm",
    "rebin_piecewise_constant_values",
    "read_aer_line_file",
    "read_hitran_par",
    "average_high_resolution_values",
    "rebin_high_resolution_values",
    "residual_by_window",
    "save_spectrum",
    "sample_high_resolution_values",
    "transmission_from_high_resolution_basis",
    "transmission_model",
    "vacuum_to_air_wavelength",
]
